spring:
  datasource:
    test1:
      driver-Class-Name: com.mysql.jdbc.Driver
      jdbc-url: mysql://localhost:3306/springboottest1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 960314


    test2:
      driver-Class-Name: com.mysql.jdbc.Driver
      jdbc-url: mysql://localhost:3306/springboottest2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 960314